version: "3.7"

services:
  web:
    build:
        context: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - 8080:8080
    volumes:
      - ./app:/code/app
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
